Dim htaPath, fso, htaFile

' Create the HTA file dynamically
Set fso = CreateObject("Scripting.FileSystemObject")
htaPath = fso.GetSpecialFolder(2) & "\PartLifecycle.hta"

Set htaFile = fso.CreateTextFile(htaPath, True)

' Write HTA content
htaFile.WriteLine "<html>"
htaFile.WriteLine "<head>"
htaFile.WriteLine "<title>Part Transaction Lifecycle Tracker</title>"
htaFile.WriteLine "<HTA:APPLICATION ID=""PartGrid"" APPLICATIONNAME=""Part Lifecycle Tracker"" SCROLL=""no"" SINGLEINSTANCE=""yes"" WINDOWSTATE=""normal"" />"
htaFile.WriteLine "<style>"
htaFile.WriteLine "* { box-sizing: border-box; }"
htaFile.WriteLine "html, body { margin:0; padding:0; height:100%; overflow-y:auto; overflow-x:hidden; background: #1e1e1e; color: #ffffff; }"
htaFile.WriteLine "body { font-family: 'Segoe UI', Arial; display: flex; flex-direction: column; }"
htaFile.WriteLine ""
htaFile.WriteLine "/* Header */"
htaFile.WriteLine "h2 { background: #2d2d30; color: #ffffff; padding: 12px; margin: 0; flex-shrink: 0; border-bottom: 1px solid #3f3f46; box-shadow: 0 2px 4px rgba(0,0,0,0.3); }"
htaFile.WriteLine ""
htaFile.WriteLine "' ===== Enhanced DB-Driven Lifecycle ====="
htaFile.WriteLine "Sub ShowLifecycle(rowIndex)"
htaFile.WriteLine "    On Error Resume Next"
htaFile.WriteLine "    Dim transID, woID"
htaFile.WriteLine "    transID = tableData(rowIndex, 0)"
htaFile.WriteLine "    woID = tableData(rowIndex, 9)"
htaFile.WriteLine "    document.getElementById(""lifecycleTitle"").innerHTML = ""Transaction Lifecycle - Trans ID: "" & transID"
htaFile.WriteLine "    document.getElementById(""lifecycleContent"").innerHTML = ""<p>Loading lifecycle...</p>"""
htaFile.WriteLine "    ShowLifecyclePanel"
htaFile.WriteLine "    BuildLifecycleFromDB transID, woID"
htaFile.WriteLine "End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "Sub BuildLifecycleFromDB(selectedTransID, woID)"
htaFile.WriteLine "    On Error Resume Next"
htaFile.WriteLine "    Dim cnn, rs, sql, hasWO"
htaFile.WriteLine "    If currentPartID = """" Then"
htaFile.WriteLine "        document.getElementById(""lifecycleContent"").innerHTML = ""<div class='no-data'>No part context.</div>"""
htaFile.WriteLine "        Exit Sub"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    hasWO = (Trim(woID) <> """")"
htaFile.WriteLine "    Set cnn = CreateObject(""ADODB.Connection"")"
htaFile.WriteLine "    cnn.ConnectionString = ""Provider=SQLOLEDB;Data Source=VISUAL;Initial Catalog=MTMFG;User ID="" & currentUser & "";Password="" & currentPassword & "";"""
htaFile.WriteLine "    cnn.Open"
htaFile.WriteLine "    If Err.Number <> 0 Then"
htaFile.WriteLine "        document.getElementById(""lifecycleContent"").innerHTML = ""<div class='no-data'>DB Connection failed: "" & Err.Description & ""</div>"""
htaFile.WriteLine "        Exit Sub"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    Dim partID : partID = currentPartID"
htaFile.WriteLine "    If hasWO Then"
htaFile.WriteLine "        sql = sql & ""DECLARE @PartID nvarchar(50)='"" & partID & ""'; DECLARE @WO nvarchar(50)='"" & woID & ""'; """
htaFile.WriteLine "        sql = sql & ""WITH events AS ("" _"
htaFile.WriteLine "            & "" SELECT 10 AS seq,'WORK ORDER' AS event_type, COALESCE(w.CREATE_DATE,GETDATE()) AS event_date, '' AS from_loc, w.WAREHOUSE_ID + ':' AS to_loc, w.DESIRED_QTY AS qty, w.BASE_ID AS ref1, w.STATUS AS ref2, CAST(NULL AS nvarchar(120)) AS trans_ids FROM WORK_ORDER w WHERE w.BASE_ID=@WO "" _"
htaFile.WriteLine "            & "" UNION ALL SELECT 20,'RECEIPT', COALESCE(r.CREATE_DATE,r.TRANSACTION_DATE), '-' , r.WAREHOUSE_ID + ':' + COALESCE(r.LOCATION_ID,''), r.QTY, 'WO:' + r.WORKORDER_BASE_ID, '' , CAST(r.TRANSACTION_ID AS nvarchar(120)) FROM INVENTORY_TRANS r WHERE r.PART_ID=@PartID AND r.WORKORDER_BASE_ID=@WO AND r.TYPE='I' "" _"
htaFile.WriteLine "            & "" UNION ALL SELECT 30,'TRANSFER', COALESCE(o.CREATE_DATE,o.TRANSACTION_DATE), o.WAREHOUSE_ID + ':' + COALESCE(o.LOCATION_ID,''), COALESCE(i.WAREHOUSE_ID,'') + ':' + COALESCE(i.LOCATION_ID,''), o.QTY, 'XFER', '', CAST(o.TRANSACTION_ID AS nvarchar(60)) + '/' + CAST(i.TRANSACTION_ID AS nvarchar(60)) FROM INVENTORY_TRANS o LEFT JOIN INVENTORY_TRANS i ON i.TRANSACTION_ID=o.TRANSFER_TRANS_ID WHERE o.PART_ID=@PartID AND o.TYPE='O' AND o.CUST_ORDER_ID IS NULL AND o.WORKORDER_BASE_ID=@WO "" _"
htaFile.WriteLine "            & "" UNION ALL SELECT 40,'SHIPMENT', COALESCE(s.CREATE_DATE,s.TRANSACTION_DATE), s.WAREHOUSE_ID + ':' + COALESCE(s.LOCATION_ID,''),'Customer', s.QTY, 'CO:' + s.CUST_ORDER_ID, '', CAST(s.TRANSACTION_ID AS nvarchar(120)) FROM INVENTORY_TRANS s WHERE s.PART_ID=@PartID AND s.TYPE='O' AND s.CUST_ORDER_ID IS NOT NULL AND s.WORKORDER_BASE_ID=@WO ) SELECT * FROM events ORDER BY event_date, seq, trans_ids;"""
htaFile.WriteLine "    Else"
htaFile.WriteLine "        sql = sql & ""DECLARE @PartID nvarchar(50)='"" & partID & ""'; """
htaFile.WriteLine "        sql = sql & ""WITH events AS ("" _"
htaFile.WriteLine "            & "" SELECT 15,'RECEIPT/IN', COALESCE(r.CREATE_DATE,r.TRANSACTION_DATE), '-' , r.WAREHOUSE_ID + ':' + COALESCE(r.LOCATION_ID,''), r.QTY, 'SRC:' + COALESCE(r.WORKORDER_BASE_ID,COALESCE(r.PURC_ORDER_ID,'')), '' , CAST(r.TRANSACTION_ID AS nvarchar(120)) FROM INVENTORY_TRANS r WHERE r.PART_ID=@PartID AND r.TYPE='I' "" _"
htaFile.WriteLine "            & "" UNION ALL SELECT 25,'TRANSFER', COALESCE(o.CREATE_DATE,o.TRANSACTION_DATE), o.WAREHOUSE_ID + ':' + COALESCE(o.LOCATION_ID,''), COALESCE(i.WAREHOUSE_ID,'') + ':' + COALESCE(i.LOCATION_ID,''), o.QTY, 'XFER', '', CAST(o.TRANSACTION_ID AS nvarchar(60)) + '/' + CAST(i.TRANSACTION_ID AS nvarchar(60)) FROM INVENTORY_TRANS o LEFT JOIN INVENTORY_TRANS i ON i.TRANSACTION_ID=o.TRANSFER_TRANS_ID WHERE o.PART_ID=@PartID AND o.TYPE='O' AND o.CUST_ORDER_ID IS NULL "" _"
htaFile.WriteLine "            & "" UNION ALL SELECT 35,'SHIPMENT', COALESCE(s.CREATE_DATE,s.TRANSACTION_DATE), s.WAREHOUSE_ID + ':' + COALESCE(s.LOCATION_ID,''),'Customer', s.QTY, 'CO:' + s.CUST_ORDER_ID, '', CAST(s.TRANSACTION_ID AS nvarchar(120)) FROM INVENTORY_TRANS s WHERE s.PART_ID=@PartID AND s.TYPE='O' AND s.CUST_ORDER_ID IS NOT NULL ) SELECT * FROM events ORDER BY event_date, seq, trans_ids;"""
htaFile.WriteLine "    End If"
htaFile.WriteLine "    Set rs = cnn.Execute(sql)"
htaFile.WriteLine "    If Err.Number <> 0 Then"
htaFile.WriteLine "        document.getElementById(""lifecycleContent"").innerHTML = ""<div class='no-data'>SQL Error: "" & Err.Description & ""</div>"""
htaFile.WriteLine "        On Error GoTo 0"
htaFile.WriteLine "        cnn.Close"
htaFile.WriteLine "        Exit Sub"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    Dim html : html = ""<h4 style='margin:0 0 8px 0;font-size:13px;'>Computed Lifecycle"""
htaFile.WriteLine "    If hasWO Then html = html & "" (WO: "" & woID & "")"""
htaFile.WriteLine "    html = html & ""</h4><div class='table-container'><table class='lifecycle-table'>"""
htaFile.WriteLine "    html = html & ""<tr><th>Date/Time</th><th>Event</th><th>From</th><th>To</th><th>Qty</th><th>Ref</th><th>Trans ID(s)</th></tr>"""
htaFile.WriteLine "    Dim lastEventType, rowClass, evtDate, isShipment, rowsCount"
htaFile.WriteLine "    rowsCount = 0"
htaFile.WriteLine "    isShipment = False"
htaFile.WriteLine "    Do While Not rs.EOF"
htaFile.WriteLine "        evtDate = rs(""event_date"")"
htaFile.WriteLine "        rowClass = """""
htaFile.WriteLine "        Select Case rs(""event_type"")"
htaFile.WriteLine "            Case ""WORK ORDER"": rowClass = ""lifecycle-wo"""
htaFile.WriteLine "            Case ""RECEIPT"", ""RECEIPT/IN"": rowClass = ""lifecycle-wo"""
htaFile.WriteLine "            Case ""TRANSFER"": rowClass = ""lifecycle-transfer"""
htaFile.WriteLine "            Case ""SHIPMENT"": rowClass = ""lifecycle-ship"""
htaFile.WriteLine "        End Select"
htaFile.WriteLine "        If rs(""event_type"") = ""SHIPMENT"" Then isShipment = True"
htaFile.WriteLine "        If InStr(CStr(rs(""trans_ids"")), selectedTransID) > 0 Then rowClass = rowClass & "" lifecycle-current"""
htaFile.WriteLine "        html = html & ""<tr class='"" & rowClass & ""'>"""
htaFile.WriteLine "        Dim dateCell"
htaFile.WriteLine "        If IsDate(evtDate) Then"
htaFile.WriteLine "            dateCell = FormatDateTime(evtDate,2) & "" "" & Right(""0"" & Hour(evtDate),2) & ":" & Right(""0"" & Minute(evtDate),2)"
htaFile.WriteLine "        Else"
htaFile.WriteLine "            dateCell = ""(no date)"""
htaFile.WriteLine "        End If"
htaFile.WriteLine "        html = html & ""<td>"" & dateCell & ""</td>"""
htaFile.WriteLine "        html = html & ""<td><b>"" & rs(""event_type"") & ""</b></td>"""
htaFile.WriteLine "        html = html & ""<td>"" & rs(""from_loc"") & ""</td>"""
htaFile.WriteLine "        html = html & ""<td>"" & rs(""to_loc"") & ""</td>"""
htaFile.WriteLine "        html = html & ""<td align='right'>"" & FormatNumber(rs(""qty""),2) & ""</td>"""
htaFile.WriteLine "        html = html & ""<td>"" & rs(""ref1"") & ""</td>"""
htaFile.WriteLine "        Dim tids"
htaFile.WriteLine "        If IsNull(rs(""trans_ids"")) Then"
htaFile.WriteLine "            tids = """""
htaFile.WriteLine "        Else"
htaFile.WriteLine "            tids = rs(""trans_ids"")"
htaFile.WriteLine "        End If"
htaFile.WriteLine "        html = html & ""<td>"" & tids & ""</td></tr>"""
htaFile.WriteLine "        rowsCount = rowsCount + 1"
htaFile.WriteLine "        rs.MoveNext"
htaFile.WriteLine "    Loop"
htaFile.WriteLine "    rs.Close"
htaFile.WriteLine "    ' Append current location if not shipped'"
htaFile.WriteLine "    If Not isShipment And rowsCount > 0 Then"
htaFile.WriteLine "        html = html & ""<tr class='lifecycle-matched'><td colspan='7'><i>Current Status: Not yet shipped. Last known location shown above.</i></td></tr>"""
htaFile.WriteLine "    ElseIf rowsCount = 0 Then"
htaFile.WriteLine "        html = html & ""<tr><td colspan='7'><i>No lifecycle events found for this context.</i></td></tr>"""
htaFile.WriteLine "    End If"
htaFile.WriteLine "    html = html & ""</table></div>"""
htaFile.WriteLine "    html = html & ""<p style='font-size:10px;margin-top:6px;color:#cccccc;'>Legend: <span style='background:#1a4c2e;padding:2px 6px;border-radius:3px;margin-right:4px;'>Receipt</span><span style='background:#4c3a1a;padding:2px 6px;border-radius:3px;margin-right:4px;'>Transfer</span><span style='background:#4c1a1a;padding:2px 6px;border-radius:3px;margin-right:4px;'>Shipment</span><span style='background:#ffd700;color:#000;padding:2px 6px;border-radius:3px;margin-right:4px;'>Selected</span></p>"""
htaFile.WriteLine "    document.getElementById(""lifecycleContent"").innerHTML = html"
htaFile.WriteLine "    cnn.Close"
htaFile.WriteLine "End Sub"
htaFile.WriteLine "' ===== End Enhanced Lifecycle =====" 
htaFile.WriteLine "        </div>"
htaFile.WriteLine "        <div id=""lifecycleContent"" class=""lifecycle-content"">"
htaFile.WriteLine "            <div class=""no-data"">Select a transaction below to view its lifecycle</div>"
htaFile.WriteLine "        </div>"
htaFile.WriteLine "    </div>"
htaFile.WriteLine "    "
htaFile.WriteLine "    <!-- Results Panel -->"
htaFile.WriteLine "    <div id=""resultsPanel"" class=""results-panel"">"
htaFile.WriteLine "        <div class=""results-header"" onclick=""ToggleResults"">"
htaFile.WriteLine "            <span id=""resultsTitle"">Transaction Results</span>"
htaFile.WriteLine "            <span id=""resultsToggleIcon"" class=""toggle-icon"">▼</span>"
htaFile.WriteLine "        </div>"
htaFile.WriteLine "        <div id=""resultsContent"" class=""results-content"">"
htaFile.WriteLine "            <div id=""content"">Enter a Part ID and click 'Load Transactions' to begin...</div>"
htaFile.WriteLine "        </div>"
htaFile.WriteLine "    </div>"
htaFile.WriteLine "</div>"
htaFile.WriteLine ""
htaFile.WriteLine "<script language=""VBScript"">"
htaFile.WriteLine "Dim conn, allData, currentPartID, tableData, rowCount, selectedRow"
htaFile.WriteLine "Dim sortColumn, sortAscending, searchMode, currentUser, currentPassword"
htaFile.WriteLine "currentPartID = """""
htaFile.WriteLine "selectedRow = -1"
htaFile.WriteLine "sortColumn = -1"
htaFile.WriteLine "sortAscending = True"
htaFile.WriteLine "currentUser = """""
htaFile.WriteLine "currentPassword = """""
htaFile.WriteLine "rowCount = 0"
htaFile.WriteLine "searchMode = ""normal"" ' normal or today"
htaFile.WriteLine "ReDim tableData(1000, 11)"
htaFile.WriteLine ""
htaFile.WriteLine "Sub Window_OnLoad"
htaFile.WriteLine "    ' Prompt for user credentials"
htaFile.WriteLine "    currentUser = InputBox(""Enter your username:"", ""Login Required"", """")"
htaFile.WriteLine "    If currentUser = """" Then"
htaFile.WriteLine "        MsgBox ""Username is required. Application will close."", vbExclamation"
htaFile.WriteLine "        window.close"
htaFile.WriteLine "        Exit Sub"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    "
htaFile.WriteLine "    currentPassword = InputBox(""Enter your password:"", ""Login Required"", """")"
htaFile.WriteLine "    If currentPassword = """" Then"
htaFile.WriteLine "        MsgBox ""Password is required. Application will close."", vbExclamation"
htaFile.WriteLine "        window.close"
htaFile.WriteLine "        Exit Sub"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    "
htaFile.WriteLine "    window.resizeTo 1050, 675"
htaFile.WriteLine "    Dim sw, sh"
htaFile.WriteLine "    sw = window.screen.availWidth"
htaFile.WriteLine "    sh = window.screen.availHeight"
htaFile.WriteLine "    window.moveTo (sw - 1050) / 2, (sh - 675) / 2"
htaFile.WriteLine "    document.getElementById(""partIDInput"").focus"
htaFile.WriteLine "    "
htaFile.WriteLine "    ' Set default date range (last 30 days to today)"
htaFile.WriteLine "    Dim today, fromDay"
htaFile.WriteLine "    today = Date"
htaFile.WriteLine "    fromDay = DateAdd(""d"", -30, today)"
htaFile.WriteLine "    document.getElementById(""toDate"").value = FormatDateTime(today, 2)"
htaFile.WriteLine "    document.getElementById(""fromDate"").value = FormatDateTime(fromDay, 2)"
htaFile.WriteLine "End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "Sub ToggleLifecycle"
htaFile.WriteLine "    Dim content, icon"
htaFile.WriteLine "    Set content = document.getElementById(""lifecycleContent"")"
htaFile.WriteLine "    Set icon = document.getElementById(""toggleIcon"")"
htaFile.WriteLine "    "
htaFile.WriteLine "    If content.className = ""lifecycle-content"" Then"
htaFile.WriteLine "        content.className = ""lifecycle-content show"""
htaFile.WriteLine "        icon.innerHTML = ""▲"""
htaFile.WriteLine "    Else"
htaFile.WriteLine "        content.className = ""lifecycle-content"""
htaFile.WriteLine "        icon.innerHTML = ""▼"""
htaFile.WriteLine "    End If"
htaFile.WriteLine "End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "Sub ToggleResults"
htaFile.WriteLine "    Dim content, icon"
htaFile.WriteLine "    Set content = document.getElementById(""resultsContent"")"
htaFile.WriteLine "    Set icon = document.getElementById(""resultsToggleIcon"")"
htaFile.WriteLine "    "
htaFile.WriteLine "    If content.className = ""results-content hide"" Then"
htaFile.WriteLine "        content.className = ""results-content"""
htaFile.WriteLine "        icon.innerHTML = ""▼"""
htaFile.WriteLine "    Else"
htaFile.WriteLine "        content.className = ""results-content hide"""
htaFile.WriteLine "        icon.innerHTML = ""▶"""
htaFile.WriteLine "    End If"
htaFile.WriteLine "End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "Sub ShowLifecyclePanel"
htaFile.WriteLine "    document.getElementById(""lifecyclePanel"").style.display = ""block"""
htaFile.WriteLine "    document.getElementById(""lifecycleContent"").className = ""lifecycle-content show"""
htaFile.WriteLine "    document.getElementById(""toggleIcon"").innerHTML = ""▲"""
htaFile.WriteLine "    document.getElementsByClassName(""main-container"")(0).scrollTop = 0"
htaFile.WriteLine "End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "Sub LoadData"
htaFile.WriteLine "    On Error Resume Next"
htaFile.WriteLine "    Dim partID, rs, sql, fromDate, toDate"
htaFile.WriteLine "    "
htaFile.WriteLine "    partID = Trim(document.getElementById(""partIDInput"").value)"
htaFile.WriteLine "    If partID = """" Then"
htaFile.WriteLine "        MsgBox ""Please enter a Part ID"", vbExclamation"
htaFile.WriteLine "        Exit Sub"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    "
htaFile.WriteLine "    fromDate = document.getElementById(""fromDate"").value"
htaFile.WriteLine "    toDate = document.getElementById(""toDate"").value"
htaFile.WriteLine "    "
htaFile.WriteLine "    currentPartID = partID"
htaFile.WriteLine "    selectedRow = -1"
htaFile.WriteLine "    searchMode = ""normal"""
htaFile.WriteLine "    document.getElementById(""status"").innerText = ""Loading..."""
htaFile.WriteLine "    document.getElementById(""lifecyclePanel"").style.display = ""none"""
htaFile.WriteLine "    "
htaFile.WriteLine "    Set conn = CreateObject(""ADODB.Connection"")"
htaFile.WriteLine "    conn.ConnectionString = ""Provider=SQLOLEDB;Data Source=VISUAL;Initial Catalog=MTMFG;User ID="" & currentUser & "";Password="" & currentPassword & "";"""
htaFile.WriteLine "    conn.Open"
htaFile.WriteLine "    "
htaFile.WriteLine "    If Err.Number <> 0 Then"
htaFile.WriteLine "        document.getElementById(""status"").innerText = ""Connection failed: "" & Err.Description"
htaFile.WriteLine "        Exit Sub"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    "
htaFile.WriteLine "    sql = ""SELECT TOP 1000 TRANSACTION_ID, TRANSACTION_DATE, CREATE_DATE, TYPE, QTY, "" & _"
htaFile.WriteLine "          ""WAREHOUSE_ID, LOCATION_ID, USER_ID, DESCRIPTION, "" & _"
htaFile.WriteLine "          ""WORKORDER_BASE_ID, WORKORDER_LOT_ID, CUST_ORDER_ID, PURC_ORDER_ID "" & _"
htaFile.WriteLine "          ""FROM INVENTORY_TRANS WHERE PART_ID = '"" & partID & ""'"""
htaFile.WriteLine "    "
htaFile.WriteLine "    ' Add date filtering if dates are provided"
htaFile.WriteLine "    If fromDate <> """" And toDate <> """" Then"
htaFile.WriteLine "        sql = sql & "" AND CAST(COALESCE(CREATE_DATE, TRANSACTION_DATE) AS DATE) BETWEEN '"" & fromDate & ""' AND '"" & toDate & ""'"""
htaFile.WriteLine "    ElseIf fromDate <> """" Then"
htaFile.WriteLine "        sql = sql & "" AND CAST(COALESCE(CREATE_DATE, TRANSACTION_DATE) AS DATE) >= '"" & fromDate & ""'"""
htaFile.WriteLine "    ElseIf toDate <> """" Then"
htaFile.WriteLine "        sql = sql & "" AND CAST(COALESCE(CREATE_DATE, TRANSACTION_DATE) AS DATE) <= '"" & toDate & ""'"""
htaFile.WriteLine "    End If"
htaFile.WriteLine "    "
htaFile.WriteLine "    sql = sql & "" ORDER BY CREATE_DATE DESC, TRANSACTION_ID DESC"""
htaFile.WriteLine "    "
htaFile.WriteLine "    Set rs = conn.Execute(sql)"
htaFile.WriteLine "    "
htaFile.WriteLine "    If Err.Number <> 0 Then"
htaFile.WriteLine "        document.getElementById(""status"").innerText = ""SQL Error: "" & Err.Description"
htaFile.WriteLine "        conn.Close"
htaFile.WriteLine "        Exit Sub"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    "
htaFile.WriteLine "    rowCount = 0"
htaFile.WriteLine "    "
htaFile.WriteLine "    If Not rs.EOF Then"
htaFile.WriteLine "        Do While Not rs.EOF And rowCount < 1000"
htaFile.WriteLine "            tableData(rowCount, 0) = rs(""TRANSACTION_ID"")"
htaFile.WriteLine "            "
htaFile.WriteLine "            If Not IsNull(rs(""CREATE_DATE"")) Then"
htaFile.WriteLine "                tableData(rowCount, 1) = FormatDateTime(rs(""CREATE_DATE""), 2)"
htaFile.WriteLine "                tableData(rowCount, 2) = FormatDateTime(rs(""CREATE_DATE""), 4)"
htaFile.WriteLine "                tableData(rowCount, 10) = rs(""CREATE_DATE"")"
htaFile.WriteLine "            Else"
htaFile.WriteLine "                tableData(rowCount, 1) = FormatDateTime(rs(""TRANSACTION_DATE""), 2)"
htaFile.WriteLine "                tableData(rowCount, 2) = ""00:00"""
htaFile.WriteLine "                tableData(rowCount, 10) = rs(""TRANSACTION_DATE"")"
htaFile.WriteLine "            End If"
htaFile.WriteLine "            "
htaFile.WriteLine "            tableData(rowCount, 3) = rs(""TYPE"")"
htaFile.WriteLine "            tableData(rowCount, 4) = rs(""QTY"")"
htaFile.WriteLine "            tableData(rowCount, 5) = rs(""WAREHOUSE_ID"")"
htaFile.WriteLine "            tableData(rowCount, 6) = rs(""LOCATION_ID"") & """""
htaFile.WriteLine "            "
htaFile.WriteLine "            Dim ref"
htaFile.WriteLine "            ref = """""
htaFile.WriteLine "            If Not IsNull(rs(""WORKORDER_BASE_ID"")) Then "
htaFile.WriteLine "                ref = ""WO: "" & rs(""WORKORDER_BASE_ID"")"
htaFile.WriteLine "            ElseIf Not IsNull(rs(""CUST_ORDER_ID"")) Then "
htaFile.WriteLine "                ref = ""CO: "" & rs(""CUST_ORDER_ID"")"
htaFile.WriteLine "            ElseIf Not IsNull(rs(""PURC_ORDER_ID"")) Then "
htaFile.WriteLine "                ref = ""PO: "" & rs(""PURC_ORDER_ID"")"
htaFile.WriteLine "            End If"
htaFile.WriteLine "            tableData(rowCount, 7) = ref"
htaFile.WriteLine "            "
htaFile.WriteLine "            tableData(rowCount, 8) = rs(""USER_ID"")"
htaFile.WriteLine "            "
htaFile.WriteLine "            If Not IsNull(rs(""WORKORDER_BASE_ID"")) Then"
htaFile.WriteLine "                tableData(rowCount, 9) = rs(""WORKORDER_BASE_ID"")"
htaFile.WriteLine "            Else"
htaFile.WriteLine "                tableData(rowCount, 9) = """""
htaFile.WriteLine "            End If"
htaFile.WriteLine "            "
htaFile.WriteLine "            If rs(""TYPE"") = ""I"" And Not IsNull(rs(""WORKORDER_BASE_ID"")) Then"
htaFile.WriteLine "                tableData(rowCount, 11) = ""receipt"""
htaFile.WriteLine "            ElseIf rs(""TYPE"") = ""I"" Then"
htaFile.WriteLine "                tableData(rowCount, 11) = ""transfer-in"""
htaFile.WriteLine "            ElseIf rs(""TYPE"") = ""O"" And Not IsNull(rs(""CUST_ORDER_ID"")) Then"
htaFile.WriteLine "                tableData(rowCount, 11) = ""shipment"""
htaFile.WriteLine "            ElseIf rs(""TYPE"") = ""O"" Then"
htaFile.WriteLine "                tableData(rowCount, 11) = ""transfer-out"""
htaFile.WriteLine "            Else"
htaFile.WriteLine "                tableData(rowCount, 11) = """""
htaFile.WriteLine "            End If"
htaFile.WriteLine "            "
htaFile.WriteLine "            rowCount = rowCount + 1"
htaFile.WriteLine "            rs.MoveNext"
htaFile.WriteLine "        Loop"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    "
htaFile.WriteLine "    rs.Close"
htaFile.WriteLine "    conn.Close"
htaFile.WriteLine "    "
htaFile.WriteLine "    DisplayTable"
htaFile.WriteLine "    document.getElementById(""status"").innerText = ""Loaded "" & rowCount & "" transactions"""
htaFile.WriteLine "End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "Sub LoadTodaysTransactions"
htaFile.WriteLine "    On Error Resume Next"
htaFile.WriteLine "    Dim rs, sql"
htaFile.WriteLine "    "
htaFile.WriteLine "    currentPartID = ""Today's Transactions"""
htaFile.WriteLine "    selectedRow = -1"
htaFile.WriteLine "    searchMode = ""today"""
htaFile.WriteLine "    document.getElementById(""status"").innerText = ""Loading today's transactions..."""
htaFile.WriteLine "    document.getElementById(""lifecyclePanel"").style.display = ""none"""
htaFile.WriteLine "    "
htaFile.WriteLine "    Set conn = CreateObject(""ADODB.Connection"")"
htaFile.WriteLine "    conn.ConnectionString = ""Provider=SQLOLEDB;Data Source=VISUAL;Initial Catalog=MTMFG;User ID="" & currentUser & "";Password="" & currentPassword & "";"""
htaFile.WriteLine "    conn.Open"
htaFile.WriteLine "    "
htaFile.WriteLine "    If Err.Number <> 0 Then"
htaFile.WriteLine "        document.getElementById(""status"").innerText = ""Connection failed: "" & Err.Description"
htaFile.WriteLine "        Exit Sub"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    "
htaFile.WriteLine "    sql = ""SELECT TOP 200 TRANSACTION_ID, TRANSACTION_DATE, CREATE_DATE, TYPE, QTY, "" & _"
htaFile.WriteLine "          ""WAREHOUSE_ID, LOCATION_ID, USER_ID, DESCRIPTION, PART_ID, "" & _"
htaFile.WriteLine "          ""WORKORDER_BASE_ID, WORKORDER_LOT_ID, CUST_ORDER_ID, PURC_ORDER_ID "" & _"
htaFile.WriteLine "          ""FROM INVENTORY_TRANS WHERE CAST(COALESCE(CREATE_DATE, TRANSACTION_DATE) AS DATE) = CAST(GETDATE() AS DATE) "" & _"
htaFile.WriteLine "          ""AND USER_ID = '"" & currentUser & ""' "" & _"
htaFile.WriteLine "          ""ORDER BY CREATE_DATE DESC, TRANSACTION_ID DESC"""
htaFile.WriteLine "    "
htaFile.WriteLine "    Set rs = conn.Execute(sql)"
htaFile.WriteLine "    "
htaFile.WriteLine "    If Err.Number <> 0 Then"
htaFile.WriteLine "        document.getElementById(""status"").innerText = ""SQL Error: "" & Err.Description"
htaFile.WriteLine "        conn.Close"
htaFile.WriteLine "        Exit Sub"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    "
htaFile.WriteLine "    ' Load raw data first"
htaFile.WriteLine "    Dim rawData(), rawCount"
htaFile.WriteLine "    rawCount = 0"
htaFile.WriteLine "    ReDim rawData(200, 11)"
htaFile.WriteLine "    "
htaFile.WriteLine "    If Not rs.EOF Then"
htaFile.WriteLine "        Do While Not rs.EOF And rawCount < 200"
htaFile.WriteLine "            rawData(rawCount, 0) = rs(""TRANSACTION_ID"")"
htaFile.WriteLine "            rawData(rawCount, 3) = rs(""TYPE"")"
htaFile.WriteLine "            rawData(rawCount, 4) = rs(""QTY"")"
htaFile.WriteLine "            rawData(rawCount, 5) = rs(""WAREHOUSE_ID"")"
htaFile.WriteLine "            rawData(rawCount, 8) = rs(""USER_ID"")"
htaFile.WriteLine "            rawData(rawCount, 9) = rs(""PART_ID"")"
htaFile.WriteLine "            rawData(rawCount, 11) = rs(""LOCATION_ID"")"
htaFile.WriteLine "            "
htaFile.WriteLine "            If Not IsNull(rs(""CREATE_DATE"")) Then"
htaFile.WriteLine "                rawData(rawCount, 1) = FormatDateTime(rs(""CREATE_DATE""), 2)"
htaFile.WriteLine "                rawData(rawCount, 2) = FormatDateTime(rs(""CREATE_DATE""), 4)"
htaFile.WriteLine "                rawData(rawCount, 10) = rs(""CREATE_DATE"")"
htaFile.WriteLine "            Else"
htaFile.WriteLine "                rawData(rawCount, 1) = FormatDateTime(rs(""TRANSACTION_DATE""), 2)"
htaFile.WriteLine "                rawData(rawCount, 2) = ""00:00"""
htaFile.WriteLine "                rawData(rawCount, 10) = rs(""TRANSACTION_DATE"")"
htaFile.WriteLine "            End If"
htaFile.WriteLine "            "
htaFile.WriteLine "            Dim ref"
htaFile.WriteLine "            ref = """""
htaFile.WriteLine "            If Not IsNull(rs(""WORKORDER_BASE_ID"")) Then "
htaFile.WriteLine "                ref = ""WO: "" & rs(""WORKORDER_BASE_ID"")"
htaFile.WriteLine "            ElseIf Not IsNull(rs(""CUST_ORDER_ID"")) Then "
htaFile.WriteLine "                ref = ""CO: "" & rs(""CUST_ORDER_ID"")"
htaFile.WriteLine "            ElseIf Not IsNull(rs(""PURC_ORDER_ID"")) Then "
htaFile.WriteLine "                ref = ""PO: "" & rs(""PURC_ORDER_ID"")"
htaFile.WriteLine "            End If"
htaFile.WriteLine "            rawData(rawCount, 7) = ref"
htaFile.WriteLine "            "
htaFile.WriteLine "            rawCount = rawCount + 1"
htaFile.WriteLine "            rs.MoveNext"
htaFile.WriteLine "        Loop"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    "
htaFile.WriteLine "    rs.Close"
htaFile.WriteLine "    conn.Close"
htaFile.WriteLine "    "
htaFile.WriteLine "    ' Now process into combined transfers"
htaFile.WriteLine "    ProcessTodaysTransfers rawData, rawCount"
htaFile.WriteLine "    DisplayTodaysTable"
htaFile.WriteLine "    document.getElementById(""status"").innerText = ""Loaded "" & rowCount & "" transaction groups for today"""
htaFile.WriteLine "End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "Sub ProcessTodaysTransfers(rawData, rawCount)"
htaFile.WriteLine "    On Error Resume Next"
htaFile.WriteLine "    rowCount = 0"
htaFile.WriteLine "    If rawCount = 0 Then Exit Sub"
htaFile.WriteLine "    "
htaFile.WriteLine "    ' Sort raw data by time ascending"
htaFile.WriteLine "    Dim i, j, k, tmp"
htaFile.WriteLine "    For i = 0 To rawCount - 2"
htaFile.WriteLine "        For j = 0 To rawCount - i - 2"
htaFile.WriteLine "            If CDate(rawData(j, 10)) > CDate(rawData(j+1, 10)) Then"
htaFile.WriteLine "                For k = 0 To 11"
htaFile.WriteLine "                    tmp = rawData(j, k)"
htaFile.WriteLine "                    rawData(j, k) = rawData(j+1, k)"
htaFile.WriteLine "                    rawData(j+1, k) = tmp"
htaFile.WriteLine "                Next"
htaFile.WriteLine "            End If"
htaFile.WriteLine "        Next"
htaFile.WriteLine "    Next"
htaFile.WriteLine "    "
htaFile.WriteLine "    Dim used() : ReDim used(rawCount - 1)"
htaFile.WriteLine "    For i = 0 To rawCount - 1: used(i) = 0: Next"
htaFile.WriteLine "    "
htaFile.WriteLine "    ' First pass: Work Orders (receipts)"
htaFile.WriteLine "    For i = 0 To rawCount - 1"
htaFile.WriteLine "        If used(i) = 0 And rawData(i, 3) = ""I"" And InStr(rawData(i, 7), ""WO:"") > 0 Then"
htaFile.WriteLine "            tableData(rowCount, 0) = rawData(i, 0) ' Trans ID"
htaFile.WriteLine "            tableData(rowCount, 1) = rawData(i, 1) ' Date"
htaFile.WriteLine "            tableData(rowCount, 2) = rawData(i, 2) ' Time"
htaFile.WriteLine "            tableData(rowCount, 3) = ""RECEIPT"""
htaFile.WriteLine "            tableData(rowCount, 4) = rawData(i, 4) ' Qty"
htaFile.WriteLine "            tableData(rowCount, 5) = rawData(i, 5) ' Warehouse"
htaFile.WriteLine "            tableData(rowCount, 6) = rawData(i, 9) & "" -> "" & rawData(i, 11) ' Part -> Location"
htaFile.WriteLine "            tableData(rowCount, 7) = rawData(i, 7) ' Reference"
htaFile.WriteLine "            tableData(rowCount, 8) = rawData(i, 8) ' User"
htaFile.WriteLine "            tableData(rowCount, 9) = rawData(i, 9) ' Part ID"
htaFile.WriteLine "            tableData(rowCount, 10) = rawData(i, 10) ' Date obj"
htaFile.WriteLine "            tableData(rowCount, 11) = ""receipt"""
htaFile.WriteLine "            used(i) = 1"
htaFile.WriteLine "            rowCount = rowCount + 1"
htaFile.WriteLine "        End If"
htaFile.WriteLine "    Next"
htaFile.WriteLine "    "
htaFile.WriteLine "    ' Second pass: Combine transfers (OUT + IN pairs)"
htaFile.WriteLine "    For i = 0 To rawCount - 1"
htaFile.WriteLine "        If used(i) = 0 And rawData(i, 3) = ""O"" And InStr(rawData(i, 7), ""CO:"") = 0 Then"
htaFile.WriteLine "            Dim bestMatch, minTimeDiff, timeDiff"
htaFile.WriteLine "            bestMatch = -1"
htaFile.WriteLine "            minTimeDiff = 999999"
htaFile.WriteLine "            "
htaFile.WriteLine "            ' Look for matching IN within next few transactions"
htaFile.WriteLine "            For j = i + 1 To rawCount - 1"
htaFile.WriteLine "                If used(j) = 0 And rawData(j, 3) = ""I"" Then"
htaFile.WriteLine "                    If InStr(rawData(j, 7), ""WO:"") = 0 And InStr(rawData(j, 7), ""PO:"") = 0 Then"
htaFile.WriteLine "                        If Abs(CDbl(rawData(i, 4))) = Abs(CDbl(rawData(j, 4))) And rawData(i, 9) = rawData(j, 9) Then"
htaFile.WriteLine "                            timeDiff = DateDiff(""s"", rawData(i, 10), rawData(j, 10))"
htaFile.WriteLine "                            If timeDiff >= 0 And timeDiff < 300 Then ' Within 5 minutes"
htaFile.WriteLine "                                If timeDiff < minTimeDiff Then"
htaFile.WriteLine "                                    minTimeDiff = timeDiff"
htaFile.WriteLine "                                    bestMatch = j"
htaFile.WriteLine "                                End If"
htaFile.WriteLine "                            End If"
htaFile.WriteLine "                        End If"
htaFile.WriteLine "                    End If"
htaFile.WriteLine "                End If"
htaFile.WriteLine "            Next"
htaFile.WriteLine "            "
htaFile.WriteLine "            If bestMatch <> -1 Then"
htaFile.WriteLine "                ' Combined transfer entry"
htaFile.WriteLine "                tableData(rowCount, 0) = rawData(i, 0) & ""/"" & rawData(bestMatch, 0)"
htaFile.WriteLine "                tableData(rowCount, 1) = rawData(i, 1)"
htaFile.WriteLine "                tableData(rowCount, 2) = rawData(i, 2)"
htaFile.WriteLine "                tableData(rowCount, 3) = ""TRANSFER"""
htaFile.WriteLine "                tableData(rowCount, 4) = rawData(i, 4)"
htaFile.WriteLine "                tableData(rowCount, 5) = rawData(i, 5)"
htaFile.WriteLine "                tableData(rowCount, 6) = rawData(i, 9) & "": "" & rawData(i, 11) & "" -> "" & rawData(bestMatch, 11)"
htaFile.WriteLine "                tableData(rowCount, 7) = ""Transfer"""
htaFile.WriteLine "                tableData(rowCount, 8) = rawData(i, 8)"
htaFile.WriteLine "                tableData(rowCount, 9) = rawData(i, 9)"
htaFile.WriteLine "                tableData(rowCount, 10) = rawData(i, 10)"
htaFile.WriteLine "                tableData(rowCount, 11) = ""transfer-out"""
htaFile.WriteLine "                used(i) = 1"
htaFile.WriteLine "                used(bestMatch) = 1"
htaFile.WriteLine "                rowCount = rowCount + 1"
htaFile.WriteLine "            End If"
htaFile.WriteLine "        End If"
htaFile.WriteLine "    Next"
htaFile.WriteLine "    "
htaFile.WriteLine "    ' Third pass: Shipments"
htaFile.WriteLine "    For i = 0 To rawCount - 1"
htaFile.WriteLine "        If used(i) = 0 And rawData(i, 3) = ""O"" And InStr(rawData(i, 7), ""CO:"") > 0 Then"
htaFile.WriteLine "            tableData(rowCount, 0) = rawData(i, 0)"
htaFile.WriteLine "            tableData(rowCount, 1) = rawData(i, 1)"
htaFile.WriteLine "            tableData(rowCount, 2) = rawData(i, 2)"
htaFile.WriteLine "            tableData(rowCount, 3) = ""SHIPMENT"""
htaFile.WriteLine "            tableData(rowCount, 4) = rawData(i, 4)"
htaFile.WriteLine "            tableData(rowCount, 5) = rawData(i, 5)"
htaFile.WriteLine "            tableData(rowCount, 6) = rawData(i, 9) & "": "" & rawData(i, 11) & "" -> Customer"""
htaFile.WriteLine "            tableData(rowCount, 7) = rawData(i, 7)"
htaFile.WriteLine "            tableData(rowCount, 8) = rawData(i, 8)"
htaFile.WriteLine "            tableData(rowCount, 9) = rawData(i, 9)"
htaFile.WriteLine "            tableData(rowCount, 10) = rawData(i, 10)"
htaFile.WriteLine "            tableData(rowCount, 11) = ""shipment"""
htaFile.WriteLine "            used(i) = 1"
htaFile.WriteLine "            rowCount = rowCount + 1"
htaFile.WriteLine "        End If"
htaFile.WriteLine "    Next"
htaFile.WriteLine "    "
htaFile.WriteLine "    ' Fourth pass: Unmatched transactions"
htaFile.WriteLine "    For i = 0 To rawCount - 1"
htaFile.WriteLine "        If used(i) = 0 Then"
htaFile.WriteLine "            tableData(rowCount, 0) = rawData(i, 0)"
htaFile.WriteLine "            tableData(rowCount, 1) = rawData(i, 1)"
htaFile.WriteLine "            tableData(rowCount, 2) = rawData(i, 2)"
htaFile.WriteLine "            tableData(rowCount, 3) = rawData(i, 3) & "" (Solo)"""
htaFile.WriteLine "            tableData(rowCount, 4) = rawData(i, 4)"
htaFile.WriteLine "            tableData(rowCount, 5) = rawData(i, 5)"
htaFile.WriteLine "            tableData(rowCount, 6) = rawData(i, 9) & "" @ "" & rawData(i, 11)"
htaFile.WriteLine "            tableData(rowCount, 7) = rawData(i, 7)"
htaFile.WriteLine "            tableData(rowCount, 8) = rawData(i, 8)"
htaFile.WriteLine "            tableData(rowCount, 9) = rawData(i, 9)"
htaFile.WriteLine "            tableData(rowCount, 10) = rawData(i, 10)"
htaFile.WriteLine "            If rawData(i, 3) = ""I"" Then"
htaFile.WriteLine "                tableData(rowCount, 11) = ""transfer-in"""
htaFile.WriteLine "            Else"
htaFile.WriteLine "                tableData(rowCount, 11) = ""transfer-out"""
htaFile.WriteLine "            End If"
htaFile.WriteLine "            rowCount = rowCount + 1"
htaFile.WriteLine "        End If"
htaFile.WriteLine "    Next"
htaFile.WriteLine "End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "Sub DisplayTodaysTable"
htaFile.WriteLine "    Dim tableHTML, i"
htaFile.WriteLine "    "
htaFile.WriteLine "    ' Update the results panel title"
htaFile.WriteLine "    document.getElementById(""resultsTitle"").innerHTML = ""Today's Combined Transactions for "" & currentUser & "" ("" & Date & "") ("" & rowCount & "" groups)"""
htaFile.WriteLine "    "
htaFile.WriteLine "    tableHTML = ""<div class='table-container'>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<table id='dataTable'><thead><tr>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(0)'>Trans ID(s)</th>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(1)'>Date</th>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(2)'>Time</th>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(3)'>Action</th>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(4)'>Qty</th>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(5)'>Warehouse</th>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(6)'>Flow</th>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(7)'>Reference</th>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(8)'>User</th>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""</tr></thead><tbody>"""
htaFile.WriteLine "    "
htaFile.WriteLine "    For i = 0 To rowCount - 1"
htaFile.WriteLine "        Dim rowClass"
htaFile.WriteLine "        rowClass = tableData(i, 11)"
htaFile.WriteLine "        If i = selectedRow Then rowClass = rowClass & "" selected"""
htaFile.WriteLine "        "
htaFile.WriteLine "        tableHTML = tableHTML & ""<tr id='row"" & i & ""' class='"" & rowClass & ""'>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td>"" & tableData(i, 0) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td>"" & tableData(i, 1) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td>"" & tableData(i, 2) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td><b>"" & tableData(i, 3) & ""</b></td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td align='right'>"" & FormatNumber(tableData(i, 4), 2) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td>"" & tableData(i, 5) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td>"" & tableData(i, 6) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td>"" & tableData(i, 7) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td>"" & tableData(i, 8) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""</tr>"""
htaFile.WriteLine "    Next"
htaFile.WriteLine "    "
htaFile.WriteLine "    tableHTML = tableHTML & ""</tbody></table>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""</div>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<div class='legend'>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<span style='background:#1a4c2e;'>Receipt (WO)</span>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<span style='background:#4c3a1a;'>Transfer (Combined)</span>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<span style='background:#4c1a1a;'>Shipment</span>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<span style='background:#1a2e4c;'>Solo IN</span>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<span style='background:#4c2c1a;'>Solo OUT</span>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""</div>"""
htaFile.WriteLine "    "
htaFile.WriteLine "    document.getElementById(""content"").innerHTML = tableHTML"
htaFile.WriteLine "End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "Sub DisplayTable"
htaFile.WriteLine "    Dim tableHTML, i, headerText"
htaFile.WriteLine "    "
htaFile.WriteLine "    If searchMode = ""today"" Then"
htaFile.WriteLine "        headerText = ""Today's Transactions for "" & currentUser & "" ("" & Date & "")"""
htaFile.WriteLine "    Else"
htaFile.WriteLine "        headerText = ""Part: "" & currentPartID"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    "
htaFile.WriteLine "    ' Update the results panel title"
htaFile.WriteLine "    document.getElementById(""resultsTitle"").innerHTML = headerText & "" ("" & rowCount & "" records)"""
htaFile.WriteLine "    "
htaFile.WriteLine "    tableHTML = ""<div class='table-container'>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<table id='dataTable'><thead><tr>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(0)'>Trans ID</th>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(1)'>Date</th>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(2)'>Time</th>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(3)'>Type</th>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(4)'>Qty</th>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(5)'>Warehouse</th>"""
htaFile.WriteLine "    If searchMode = ""today"" Then"
htaFile.WriteLine "        tableHTML = tableHTML & ""<th onclick='SortTable(6)'>Part @ Location</th>"""
htaFile.WriteLine "    Else"
htaFile.WriteLine "        tableHTML = tableHTML & ""<th onclick='SortTable(6)'>Location</th>"""
htaFile.WriteLine "    End If"
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(7)'>Reference</th>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<th onclick='SortTable(8)'>User</th>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""</tr></thead><tbody>"""
htaFile.WriteLine "    "
htaFile.WriteLine "    For i = 0 To rowCount - 1"
htaFile.WriteLine "        Dim rowClass"
htaFile.WriteLine "        rowClass = tableData(i, 11)"
htaFile.WriteLine "        If i = selectedRow Then rowClass = rowClass & "" selected"""
htaFile.WriteLine "        "
htaFile.WriteLine "        tableHTML = tableHTML & ""<tr id='row"" & i & ""' class='"" & rowClass & ""' onclick='SelectRow "" & i & ""'>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td>"" & tableData(i, 0) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td>"" & tableData(i, 1) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td>"" & tableData(i, 2) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td>"" & tableData(i, 3) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td align='right'>"" & FormatNumber(tableData(i, 4), 2) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td>"" & tableData(i, 5) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td>"" & tableData(i, 6) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td>"" & tableData(i, 7) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""<td>"" & tableData(i, 8) & ""</td>"""
htaFile.WriteLine "        tableHTML = tableHTML & ""</tr>"""
htaFile.WriteLine "    Next"
htaFile.WriteLine "    "
htaFile.WriteLine "    tableHTML = tableHTML & ""</tbody></table>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""</div>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<div class='legend'>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<span style='background:#1a4c2e;'>Receipt (WO)</span>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<span style='background:#1a2e4c;'>Transfer IN</span>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<span style='background:#4c2c1a;'>Transfer OUT</span>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""<span style='background:#4c1a1a;'>Shipment</span>"""
htaFile.WriteLine "    tableHTML = tableHTML & ""</div>"""
htaFile.WriteLine "    "
htaFile.WriteLine "    document.getElementById(""content"").innerHTML = tableHTML"
htaFile.WriteLine "    "
htaFile.WriteLine "    If sortColumn >= 0 Then"
htaFile.WriteLine "        Dim headers"
htaFile.WriteLine "        Set headers = document.getElementById(""dataTable"").getElementsByTagName(""th"")"
htaFile.WriteLine "        If sortAscending Then"
htaFile.WriteLine "            headers(sortColumn).className = ""sorted-asc"""
htaFile.WriteLine "        Else"
htaFile.WriteLine "            headers(sortColumn).className = ""sorted-desc"""
htaFile.WriteLine "        End If"
htaFile.WriteLine "    End If"
htaFile.WriteLine "End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "Sub SelectRow(rowIndex)"
htaFile.WriteLine "    If searchMode = ""today"" Then"
htaFile.WriteLine "        ' No lifecycle view for today's transactions"
htaFile.WriteLine "        Exit Sub"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    "
htaFile.WriteLine "    If selectedRow = rowIndex Then"
htaFile.WriteLine "        ' Clicking same row again - hide lifecycle"
htaFile.WriteLine "        selectedRow = -1"
htaFile.WriteLine "        document.getElementById(""lifecyclePanel"").style.display = ""none"""
htaFile.WriteLine "    Else"
htaFile.WriteLine "        selectedRow = rowIndex"
htaFile.WriteLine "        ShowLifecycle rowIndex"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    DisplayTable"
htaFile.WriteLine "End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "' ===== Enhanced DB-Driven Lifecycle =====" 
htaFile.WriteLine "Sub ShowLifecycle(rowIndex)" 
htaFile.WriteLine "    On Error Resume Next" 
htaFile.WriteLine "    Dim transID, woID" 
htaFile.WriteLine "    transID = tableData(rowIndex, 0)" 
htaFile.WriteLine "    woID = tableData(rowIndex, 9)" 
htaFile.WriteLine "    document.getElementById(\"lifecycleTitle\").innerHTML = \"Transaction Lifecycle - Trans ID: \" & transID" 
htaFile.WriteLine "    document.getElementById(\"lifecycleContent\").innerHTML = \"<p>Loading lifecycle...</p>"" 
htaFile.WriteLine "    ShowLifecyclePanel" 
htaFile.WriteLine "    BuildLifecycleFromDB transID, woID" 
htaFile.WriteLine "End Sub" 
htaFile.WriteLine "" 
htaFile.WriteLine "Sub BuildLifecycleFromDB(selectedTransID, woID)" 
htaFile.WriteLine "    On Error Resume Next" 
htaFile.WriteLine "    Dim cnn, rs, sql, hasWO" 
htaFile.WriteLine "    If currentPartID = \"\" Then" 
htaFile.WriteLine "        document.getElementById(\"lifecycleContent\").innerHTML = \"<div class='no-data'>No part context.</div>"" 
htaFile.WriteLine "        Exit Sub" 
htaFile.WriteLine "    End If" 
htaFile.WriteLine "    hasWO = (Trim(woID) <> \"\")" 
htaFile.WriteLine "    Set cnn = CreateObject(\"ADODB.Connection\")" 
htaFile.WriteLine "    cnn.ConnectionString = \"Provider=SQLOLEDB;Data Source=VISUAL;Initial Catalog=MTMFG;User ID=\" & currentUser & \";Password=\" & currentPassword & \";\"" 
htaFile.WriteLine "    cnn.Open" 
htaFile.WriteLine "    If Err.Number <> 0 Then" 
htaFile.WriteLine "        document.getElementById(\"lifecycleContent\").innerHTML = \"<div class='no-data'>DB Connection failed: \" & Err.Description & \"</div>"" 
htaFile.WriteLine "        Exit Sub" 
htaFile.WriteLine "    End If" 
htaFile.WriteLine "    Dim partID : partID = currentPartID" 
htaFile.WriteLine "    If hasWO Then" 
htaFile.WriteLine "        sql = sql & \"DECLARE @PartID nvarchar(50)='\" & partID & \"'; DECLARE @WO nvarchar(50)='\" & woID & \"'; \"" 
htaFile.WriteLine "        sql = sql & \"WITH events AS (\" _" 
htaFile.WriteLine "            & \" SELECT 10 AS seq,'WORK ORDER' AS event_type, COALESCE(w.CREATE_DATE,GETDATE()) AS event_date, '' AS from_loc, w.WAREHOUSE_ID + ':' AS to_loc, w.DESIRED_QTY AS qty, w.BASE_ID AS ref1, w.STATUS AS ref2, CAST(NULL AS nvarchar(120)) AS trans_ids FROM WORK_ORDER w WHERE w.BASE_ID=@WO \" _" 
htaFile.WriteLine "            & \" UNION ALL SELECT 20,'RECEIPT', COALESCE(r.CREATE_DATE,r.TRANSACTION_DATE), '-' , r.WAREHOUSE_ID + ':' + COALESCE(r.LOCATION_ID,''), r.QTY, 'WO:' + r.WORKORDER_BASE_ID, '' , CAST(r.TRANSACTION_ID AS nvarchar(120)) FROM INVENTORY_TRANS r WHERE r.PART_ID=@PartID AND r.WORKORDER_BASE_ID=@WO AND r.TYPE='I' \" _" 
htaFile.WriteLine "            & \" UNION ALL SELECT 30,'TRANSFER', COALESCE(o.CREATE_DATE,o.TRANSACTION_DATE), o.WAREHOUSE_ID + ':' + COALESCE(o.LOCATION_ID,''), COALESCE(i.WAREHOUSE_ID,'') + ':' + COALESCE(i.LOCATION_ID,''), o.QTY, 'XFER', '', CAST(o.TRANSACTION_ID AS nvarchar(60)) + '/' + CAST(i.TRANSACTION_ID AS nvarchar(60)) FROM INVENTORY_TRANS o LEFT JOIN INVENTORY_TRANS i ON i.TRANSACTION_ID=o.TRANSFER_TRANS_ID WHERE o.PART_ID=@PartID AND o.TYPE='O' AND o.CUST_ORDER_ID IS NULL AND o.WORKORDER_BASE_ID=@WO \" _" 
htaFile.WriteLine "            & \" UNION ALL SELECT 40,'SHIPMENT', COALESCE(s.CREATE_DATE,s.TRANSACTION_DATE), s.WAREHOUSE_ID + ':' + COALESCE(s.LOCATION_ID,''),'Customer', s.QTY, 'CO:' + s.CUST_ORDER_ID, '', CAST(s.TRANSACTION_ID AS nvarchar(120)) FROM INVENTORY_TRANS s WHERE s.PART_ID=@PartID AND s.TYPE='O' AND s.CUST_ORDER_ID IS NOT NULL AND s.WORKORDER_BASE_ID=@WO ) SELECT * FROM events ORDER BY event_date, seq, trans_ids;"" 
htaFile.WriteLine "    Else" 
htaFile.WriteLine "        sql = sql & \"DECLARE @PartID nvarchar(50)='\" & partID & \"'; \"" 
htaFile.WriteLine "        sql = sql & \"WITH events AS (\" _" 
htaFile.WriteLine "            & \" SELECT 15,'RECEIPT/IN', COALESCE(r.CREATE_DATE,r.TRANSACTION_DATE), '-' , r.WAREHOUSE_ID + ':' + COALESCE(r.LOCATION_ID,''), r.QTY, 'SRC:' + COALESCE(r.WORKORDER_BASE_ID,COALESCE(r.PURC_ORDER_ID,'')), '' , CAST(r.TRANSACTION_ID AS nvarchar(120)) FROM INVENTORY_TRANS r WHERE r.PART_ID=@PartID AND r.TYPE='I' \" _" 
htaFile.WriteLine "            & \" UNION ALL SELECT 25,'TRANSFER', COALESCE(o.CREATE_DATE,o.TRANSACTION_DATE), o.WAREHOUSE_ID + ':' + COALESCE(o.LOCATION_ID,''), COALESCE(i.WAREHOUSE_ID,'') + ':' + COALESCE(i.LOCATION_ID,''), o.QTY, 'XFER', '', CAST(o.TRANSACTION_ID AS nvarchar(60)) + '/' + CAST(i.TRANSACTION_ID AS nvarchar(60)) FROM INVENTORY_TRANS o LEFT JOIN INVENTORY_TRANS i ON i.TRANSACTION_ID=o.TRANSFER_TRANS_ID WHERE o.PART_ID=@PartID AND o.TYPE='O' AND o.CUST_ORDER_ID IS NULL \" _" 
htaFile.WriteLine "            & \" UNION ALL SELECT 35,'SHIPMENT', COALESCE(s.CREATE_DATE,s.TRANSACTION_DATE), s.WAREHOUSE_ID + ':' + COALESCE(s.LOCATION_ID,''),'Customer', s.QTY, 'CO:' + s.CUST_ORDER_ID, '', CAST(s.TRANSACTION_ID AS nvarchar(120)) FROM INVENTORY_TRANS s WHERE s.PART_ID=@PartID AND s.TYPE='O' AND s.CUST_ORDER_ID IS NOT NULL ) SELECT * FROM events ORDER BY event_date, seq, trans_ids;"" 
htaFile.WriteLine "    End If" 
htaFile.WriteLine "    Set rs = cnn.Execute(sql)" 
htaFile.WriteLine "    If Err.Number <> 0 Then" 
htaFile.WriteLine "        document.getElementById(\"lifecycleContent\").innerHTML = \"<div class='no-data'>SQL Error: \" & Err.Description & \"</div>"" 
htaFile.WriteLine "        On Error GoTo 0" 
htaFile.WriteLine "        cnn.Close" 
htaFile.WriteLine "        Exit Sub" 
htaFile.WriteLine "    End If" 
htaFile.WriteLine "    Dim html : html = \"<h4 style='margin:0 0 8px 0;font-size:13px;'>Computed Lifecycle\"" 
htaFile.WriteLine "    If hasWO Then html = html & \" (WO: \" & woID & ")"" 
htaFile.WriteLine "    html = html & \"</h4><div class='table-container'><table class='lifecycle-table'>"" 
htaFile.WriteLine "    html = html & \"<tr><th>Date/Time</th><th>Event</th><th>From</th><th>To</th><th>Qty</th><th>Ref</th><th>Trans ID(s)</th></tr>"" 
htaFile.WriteLine "    Dim lastEventType, rowClass, evtDate, isShipment, rowsCount" 
htaFile.WriteLine "    rowsCount = 0" 
htaFile.WriteLine "    isShipment = False" 
htaFile.WriteLine "    Do While Not rs.EOF" 
htaFile.WriteLine "        evtDate = rs(\"event_date\")" 
htaFile.WriteLine "        rowClass = \"\"" 
htaFile.WriteLine "        Select Case rs(\"event_type\")" 
htaFile.WriteLine "            Case \"WORK ORDER\": rowClass = \"lifecycle-wo\"" 
htaFile.WriteLine "            Case \"RECEIPT\", \"RECEIPT/IN\": rowClass = \"lifecycle-wo\"" 
htaFile.WriteLine "            Case \"TRANSFER\": rowClass = \"lifecycle-transfer\"" 
htaFile.WriteLine "            Case \"SHIPMENT\": rowClass = \"lifecycle-ship\"" 
htaFile.WriteLine "        End Select" 
htaFile.WriteLine "        If rs(\"event_type\") = \"SHIPMENT\" Then isShipment = True" 
htaFile.WriteLine "        If InStr(CStr(rs(\"trans_ids\")), selectedTransID) > 0 Then rowClass = rowClass & \" lifecycle-current\"" 
htaFile.WriteLine "        html = html & \"<tr class='\" & rowClass & \"'>\"" 
htaFile.WriteLine "        Dim dateCell" 
htaFile.WriteLine "        If IsDate(evtDate) Then" 
htaFile.WriteLine "            dateCell = FormatDateTime(evtDate,2) & \" \" & Right(\"0\" & Hour(evtDate),2) & ":" & Right(\"0\" & Minute(evtDate),2)" 
htaFile.WriteLine "        Else" 
htaFile.WriteLine "            dateCell = \"(no date)\"" 
htaFile.WriteLine "        End If" 
htaFile.WriteLine "        html = html & \"<td>\" & dateCell & \"</td>\"" 
htaFile.WriteLine "        html = html & \"<td><b>\" & rs(\"event_type\") & \"</b></td>\"" 
htaFile.WriteLine "        html = html & \"<td>\" & rs(\"from_loc\") & \"</td>\"" 
htaFile.WriteLine "        html = html & \"<td>\" & rs(\"to_loc\") & \"</td>\"" 
htaFile.WriteLine "        html = html & \"<td align='right'>\" & FormatNumber(rs(\"qty\"),2) & \"</td>\"" 
htaFile.WriteLine "        html = html & \"<td>\" & rs(\"ref1\") & \"</td>\"" 
htaFile.WriteLine "        Dim tids" 
htaFile.WriteLine "        If IsNull(rs(\"trans_ids\")) Then" 
htaFile.WriteLine "            tids = \"\"" 
htaFile.WriteLine "        Else" 
htaFile.WriteLine "            tids = rs(\"trans_ids\")" 
htaFile.WriteLine "        End If" 
htaFile.WriteLine "        html = html & \"<td>\" & tids & \"</td></tr>\"" 
htaFile.WriteLine "        rowsCount = rowsCount + 1" 
htaFile.WriteLine "        rs.MoveNext" 
htaFile.WriteLine "    Loop" 
htaFile.WriteLine "    rs.Close" 
htaFile.WriteLine "    ' Append current location if not shipped'" 
htaFile.WriteLine "    If Not isShipment And rowsCount > 0 Then" 
htaFile.WriteLine "        html = html & \"<tr class='lifecycle-matched'><td colspan='7'><i>Current Status: Not yet shipped. Last known location shown above.</i></td></tr>"" 
htaFile.WriteLine "    ElseIf rowsCount = 0 Then" 
htaFile.WriteLine "        html = html & \"<tr><td colspan='7'><i>No lifecycle events found for this context.</i></td></tr>"" 
htaFile.WriteLine "    End If" 
htaFile.WriteLine "    html = html & \"</table></div>"" 
htaFile.WriteLine "    html = html & \"<p style='font-size:10px;margin-top:6px;color:#cccccc;'>Legend: <span style='background:#1a4c2e;padding:2px 6px;border-radius:3px;margin-right:4px;'>Receipt</span><span style='background:#4c3a1a;padding:2px 6px;border-radius:3px;margin-right:4px;'>Transfer</span><span style='background:#4c1a1a;padding:2px 6px;border-radius:3px;margin-right:4px;'>Shipment</span><span style='background:#ffd700;color:#000;padding:2px 6px;border-radius:3px;margin-right:4px;'>Selected</span></p>"" 
htaFile.WriteLine "    document.getElementById(\"lifecycleContent\").innerHTML = html" 
htaFile.WriteLine "    cnn.Close" 
htaFile.WriteLine "End Sub" 
htaFile.WriteLine "' ===== End Enhanced Lifecycle =====" 
htaFile.WriteLine ""
htaFile.WriteLine "Function GetActionDescription(transType, reference)"
htaFile.WriteLine "    If transType = ""I"" And InStr(reference, ""WO:"") > 0 Then"
htaFile.WriteLine "        GetActionDescription = ""RECEIPT from Work Order"""
htaFile.WriteLine "    ElseIf transType = ""I"" Then"
htaFile.WriteLine "        GetActionDescription = ""TRANSFER IN"""
htaFile.WriteLine "    ElseIf transType = ""O"" And InStr(reference, ""CO:"") > 0 Then"
htaFile.WriteLine "        GetActionDescription = ""SHIPMENT to Customer"""
htaFile.WriteLine "    ElseIf transType = ""O"" Then"
htaFile.WriteLine "        GetActionDescription = ""TRANSFER OUT"""
htaFile.WriteLine "    Else"
htaFile.WriteLine "        GetActionDescription = transType"
htaFile.WriteLine "    End If"
htaFile.WriteLine "End Function"
htaFile.WriteLine ""
htaFile.WriteLine "Sub SortTable(col)"
htaFile.WriteLine "    If sortColumn = col Then"
htaFile.WriteLine "        sortAscending = Not sortAscending"
htaFile.WriteLine "    Else"
htaFile.WriteLine "        sortColumn = col"
htaFile.WriteLine "        sortAscending = True"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    "
htaFile.WriteLine "    Dim i, j, temp, k"
htaFile.WriteLine "    For i = 0 To rowCount - 2"
htaFile.WriteLine "        For j = 0 To rowCount - i - 2"
htaFile.WriteLine "            Dim swap"
htaFile.WriteLine "            swap = False"
htaFile.WriteLine "            "
htaFile.WriteLine "            If col = 4 Then"
htaFile.WriteLine "                If sortAscending Then"
htaFile.WriteLine "                    If CDbl(tableData(j, col)) > CDbl(tableData(j + 1, col)) Then swap = True"
htaFile.WriteLine "                Else"
htaFile.WriteLine "                    If CDbl(tableData(j, col)) < CDbl(tableData(j + 1, col)) Then swap = True"
htaFile.WriteLine "                End If"
htaFile.WriteLine "            ElseIf col = 1 Or col = 2 Then"
htaFile.WriteLine "                If sortAscending Then"
htaFile.WriteLine "                    If CDate(tableData(j, 10)) > CDate(tableData(j + 1, 10)) Then swap = True"
htaFile.WriteLine "                Else"
htaFile.WriteLine "                    If CDate(tableData(j, 10)) < CDate(tableData(j + 1, 10)) Then swap = True"
htaFile.WriteLine "                End If"
htaFile.WriteLine "            Else"
htaFile.WriteLine "                If sortAscending Then"
htaFile.WriteLine "                    If tableData(j, col) > tableData(j + 1, col) Then swap = True"
htaFile.WriteLine "                Else"
htaFile.WriteLine "                    If tableData(j, col) < tableData(j + 1, col) Then swap = True"
htaFile.WriteLine "                End If"
htaFile.WriteLine "            End If"
htaFile.WriteLine "            "
htaFile.WriteLine "            If swap Then"
htaFile.WriteLine "                For k = 0 To 11"
htaFile.WriteLine "                    temp = tableData(j, k)"
htaFile.WriteLine "                    tableData(j, k) = tableData(j + 1, k)"
htaFile.WriteLine "                    tableData(j + 1, k) = temp"
htaFile.WriteLine "                Next"
htaFile.WriteLine "            End If"
htaFile.WriteLine "        Next"
htaFile.WriteLine "    Next"
htaFile.WriteLine "    "
htaFile.WriteLine "    DisplayTable"
htaFile.WriteLine "End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "Sub ExportData"
htaFile.WriteLine "    If rowCount = 0 Then"
htaFile.WriteLine "        MsgBox ""No data to export"", vbInformation"
htaFile.WriteLine "        Exit Sub"
htaFile.WriteLine "    End If"
htaFile.WriteLine "    "
htaFile.WriteLine "    Dim fso, file, fileName, i, exportText"
htaFile.WriteLine "    Set fso = CreateObject(""Scripting.FileSystemObject"")"
htaFile.WriteLine "    fileName = fso.GetSpecialFolder(2) & ""\PartTrans_"" & currentPartID & ""_"" & Replace(Date, ""/"", """") & "".txt"""
htaFile.WriteLine "    "
htaFile.WriteLine "    exportText = ""Trans ID"" & vbTab & ""Date"" & vbTab & ""Time"" & vbTab & ""Type"" & vbTab"
htaFile.WriteLine "    exportText = exportText & ""Qty"" & vbTab & ""Warehouse"" & vbTab & ""Location"" & vbTab"
htaFile.WriteLine "    exportText = exportText & ""Reference"" & vbTab & ""User"" & vbCrLf"
htaFile.WriteLine "    "
htaFile.WriteLine "    For i = 0 To rowCount - 1"
htaFile.WriteLine "        exportText = exportText & tableData(i, 0) & vbTab"
htaFile.WriteLine "        exportText = exportText & tableData(i, 1) & vbTab"
htaFile.WriteLine "        exportText = exportText & tableData(i, 2) & vbTab"
htaFile.WriteLine "        exportText = exportText & tableData(i, 3) & vbTab"
htaFile.WriteLine "        exportText = exportText & tableData(i, 4) & vbTab"
htaFile.WriteLine "        exportText = exportText & tableData(i, 5) & vbTab"
htaFile.WriteLine "        exportText = exportText & tableData(i, 6) & vbTab"
htaFile.WriteLine "        exportText = exportText & tableData(i, 7) & vbTab"
htaFile.WriteLine "        exportText = exportText & tableData(i, 8) & vbCrLf"
htaFile.WriteLine "    Next"
htaFile.WriteLine "    "
htaFile.WriteLine "    Set file = fso.CreateTextFile(fileName, True)"
htaFile.WriteLine "    file.Write exportText"
htaFile.WriteLine "    file.Close"
htaFile.WriteLine "    MsgBox ""Exported to: "" & fileName, vbInformation"
htaFile.WriteLine "End Sub"
htaFile.WriteLine "</script>"
htaFile.WriteLine "</body>"
htaFile.WriteLine "</html>"

htaFile.Close

' Launch the HTA
CreateObject("WScript.Shell").Run """" & htaPath & """", 1, False